defaults:
  - base

_target_: gflownet.envs.photo.Photo

id: photo

# Policy distribution parameters
fixed_distr_params: null
random_distr_params: null
# Check if action valid with mask before step
skip_mask_check: True
# Whether the environment has conditioning variables
conditional: False
# Whether the environment is continuous
continuous: True
